### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by TongfanWeitf** [jxylon/imgcrawler-tool#9]
求助！
我在anaconda里python3.9 环境下安装 requirements， 出现了这个错误：
  error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by jxylon** [comment]
可能是在安装某个包的时候，由于等待安装的包版本太低导致的，可以尝试把后面的版本号去掉

**Comment by TongfanWeitf** [comment]
谢谢，我会试一下
